server:
  port: 8764

spring:
  main:
    web-application-type: reactive
  application:
    name: zuul-server
  cloud:
    gateway:
      routes:
        - id: user-api
          uri: lb://user-api
          predicates:
            - Path=/users/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  eureka:
    enabled: true